/**
 * BixArena API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PromptValidation {
  /**
   * The original prompt that was validated
   */
  prompt: string;
  /**
   * Confidence score indicating biomedical relevance (0.0 = not biomedical, 1.0 = definitely biomedical)
   */
  confidence: number;
  /**
   * Whether the prompt is considered biomedically related (confidence >= 0.5)
   */
  isBiomedical: boolean;
}
